"use client";
import { useState } from "react";
import { solve } from "@/lib/api";
import type { RunResult } from "@/lib/types";

const TYPES = [
  { id: "exec", icon: "📊", name: "Executive summary", desc: "Business impact, plain language" },
  { id: "opt", icon: "⚙️", name: "Optimization report", desc: "Solvers, KPIs, before/after" },
  { id: "tech", icon: "🧮", name: "Technical report", desc: "Model, constraints, QUBO stats" },
];
const W = { t: 0.7, e: 0.55, d: 0.9 };
const NAME: Record<string, string> = { classical: "Classical", quantum: "Quantum-inspired", hybrid: "Hybrid quantum" };

function reportText(id: string, R: RunResult): string {
  const b = R.base, x = R.best.m, name = NAME[R.best.kind], line = "─".repeat(46);
  if (id === "exec")
    return `EXECUTIVE SUMMARY — CNC Production Scheduling
Generated by OptiTwin Studio
${line}

Winning solver     ${name}
Makespan           ${(b.makespan / 24).toFixed(1)}d → ${(x.makespan / 24).toFixed(1)}d  (${Math.round((100 * (b.makespan - x.makespan)) / b.makespan)}% faster)
Projected cost     $${Math.round(R.baseMoney / 1000)}K → $${Math.round(R.bestMoney / 1000)}K
Energy saved       ${Math.round((100 * (b.energy - x.energy)) / b.energy)}%
Utilization        ${Math.round(b.util * 100)}% → ${Math.round(x.util * 100)}%
On-time delivery   ${(x.onTime * 100).toFixed(1)}%
Confidence         ${R.improvePct}% improvement over baseline

RECOMMENDATION
Apply the ${name.toLowerCase()} schedule and monitor the QC buffer for the first shift.`;
  if (id === "opt")
    return `OPTIMIZATION REPORT
${line}

Solver comparison
${R.solvers.map((s) => `  ${s.kind.padEnd(11)} time ${(s.time + "s").padEnd(6)} quality ${(s.quality + "%").padEnd(5)} cost ${s.cost.toFixed(3)}`).join("\n")}

Best: ${name} — ${R.improvePct}% better than the naive baseline.
Objective: minimize makespan + energy, maximize on-time (weighted per sliders).`;
  return `TECHNICAL REPORT
${line}

Formulation   Mixed-Integer Program
Decision vars x[i,j,t] ∈ {0,1}, s[i] ≥ 0
Instance      20 machines · 250 jobs · 3 shifts
Constraints   maintenance, ≤16h/day, peak cap, deadlines, tier priority
QUBO          5000×5000 upper-triangular, penalty λ=8.0
Embedding     Pegasus P16, ~1,842 qubits, 1000 reads
Solver        LPT greedy warm-start + simulated annealing local search`;
}

function reportCsv(R: RunResult): string {
  const b = R.base, x = R.best.m;
  let s = "solver,time_s,quality_pct,cost\n";
  R.solvers.forEach((v) => (s += `${v.kind},${v.time},${v.quality},${v.cost.toFixed(4)}\n`));
  s += `\nmetric,baseline,optimized\n`;
  s += `makespan_h,${b.makespan.toFixed(1)},${x.makespan.toFixed(1)}\n`;
  s += `energy_kwh,${b.energy.toFixed(0)},${x.energy.toFixed(0)}\n`;
  s += `utilization,${b.util.toFixed(3)},${x.util.toFixed(3)}\n`;
  s += `on_time,${b.onTime.toFixed(3)},${x.onTime.toFixed(3)}\n`;
  s += `cost_usd,${R.baseMoney.toFixed(0)},${R.bestMoney.toFixed(0)}\n`;
  return s;
}

function download(name: string, text: string, type: string) {
  const url = URL.createObjectURL(new Blob([text], { type }));
  const a = document.createElement("a");
  a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url);
}

export default function Reports() {
  const [pick, setPick] = useState("exec");
  const [preview, setPreview] = useState("Select a report type and hit Generate.");

  const gen = async () => setPreview(reportText(pick, await solve(W)));
  const csv = async () => download(`optitwin-${pick}.csv`, reportCsv(await solve(W)), "text/csv");
  const print = async () => { setPreview(reportText(pick, await solve(W))); setTimeout(() => window.print(), 80); };

  return (
    <>
      <div className="page-head stagger">
        <div>
          <div className="page-title">Generate a <span className="serif">report</span></div>
          <div className="page-sub">Turn the latest optimization into a shareable document — built from live engine output.</div>
        </div>
      </div>

      <div className="split">
        <div className="card glass card-pad stagger">
          <div className="card-head"><h3>Report type</h3><span className="link">{TYPES.find((t) => t.id === pick)!.name}</span></div>
          <div className="solver-opts">
            {TYPES.map((t) => (
              <div key={t.id} className={"solver" + (pick === t.id ? " on" : "")} onClick={() => setPick(t.id)}>
                <div className="chk"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={3}><path d="M5 12l4 4 10-10" /></svg></div>
                <div className="sic" style={{ fontSize: 16 }}>{t.icon}</div>
                <div className="sn">{t.name}</div><div className="sd">{t.desc}</div>
              </div>
            ))}
          </div>
          <div style={{ display: "flex", gap: 10, marginTop: 18 }}>
            <button className="btn" onClick={csv} style={{ flex: 1, justifyContent: "center" }}>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8}><path d="M12 3v12m0 0l-4-4m4 4l4-4M4 21h16" /></svg>Download CSV
            </button>
            <button className="btn primary" onClick={gen} style={{ flex: 1, justifyContent: "center" }}>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8}><path d="M12 3l1.9 4.6L18.5 9l-4.6 1.9L12 15l-1.9-4.1L5.5 9l4.6-1.4L12 3z" /></svg>Generate
            </button>
          </div>
        </div>

        <div className="card glass card-pad stagger">
          <div className="card-head"><h3>Preview</h3><span className="link" onClick={print} style={{ cursor: "pointer" }}>Print / Save PDF</span></div>
          <div id="repPreview" className="mono" style={{ fontSize: 12.5, color: "var(--text-dim)", lineHeight: 1.75, whiteSpace: "pre-wrap", minHeight: 220 }}>{preview}</div>
        </div>
      </div>
    </>
  );
}
